name: CI/CD - Build

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
      
jobs:
  build:
    name: Build projeto
    runs-on: Ubuntu 24.04.4 LTS
    
    steps:
      - name: Checkout do repositório
        uses: action/checkout@v4
        
      - name: Configuração Java 24
        uses: actions/setup-java@v4
        with:
<<<<<<< HEAD
          java-version: '24.0.1'
=======
          java-version: '24'
>>>>>>> 5d3589724238179f6feccc532374b73060c60bb6
          distribution: 'temurin'
          cache: maven
          
      - name: Build da aplicação
        run: mvn clean package -DskipTest
      
      - name: Salvar
        uses: action/upload-artifact@v4
        with:
             name: app-war
             path: target/*.war
             retention-day: 7

